# Generated by Django 4.2.7 on 2023-11-05 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0004_alter_book_authors"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="published_date",
            field=models.DateField(null=True),
        ),
    ]
