# Generated by Django 4.2.7 on 2023-11-05 21:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0006_alter_book_published_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="categories",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=150, null=True),
                null=True,
                size=None,
            ),
        ),
    ]
