# Generated by Django 4.2.7 on 2023-11-05 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0007_book_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="thumbnail",
            field=models.URLField(null=True),
        ),
    ]
