# Generated by Django 4.2.7 on 2023-11-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("books", "0008_book_thumbnail"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="average_rating",
            field=models.DecimalField(decimal_places=2, max_digits=4, null=True),
        ),
        migrations.AddField(
            model_name="book",
            name="ratings_count",
            field=models.IntegerField(null=True),
        ),
    ]
